"""refactor_add_alert_rule_alert_history_audit_log_server_group

Revision ID: 51ffba2471b7
Revises: e9d3b062a07b
Create Date: 2026-03-02 20:30:30.908666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51ffba2471b7'
down_revision = 'e9d3b062a07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('username_snapshot', sa.String(length=50), nullable=True, comment='用户名快照'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='动作'),
    sa.Column('target', sa.String(length=100), nullable=True, comment='操作对象'),
    sa.Column('details', sa.Text(), nullable=True, comment='详细信息/JSON'),
    sa.Column('client_ip', sa.String(length=45), nullable=True, comment='来源IP'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分组名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分组描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='关联服务器'),
    sa.Column('metric_type', sa.String(length=20), nullable=False, comment='告警指标'),
    sa.Column('current_value', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='当时数值'),
    sa.Column('threshold_snapshot', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='当时阈值快照'),
    sa.Column('alert_content', sa.Text(), nullable=True, comment='告警邮件内容'),
    sa.Column('status', sa.Enum('firing', 'resolved', 'ignored'), nullable=True, comment='状态'),
    sa.Column('triggered_at', sa.DateTime(), nullable=True, comment='触发时间'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='恢复时间'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='关联服务器'),
    sa.Column('metric_type', sa.Enum('cpu', 'memory', 'disk'), nullable=False, comment='指标类型'),
    sa.Column('threshold', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='触发阈值(%)'),
    sa.Column('silence_minutes', sa.Integer(), nullable=True, comment='静默时间(分钟)'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_data', schema=None) as batch_op:
        batch_op.alter_column('cpu_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='CPU',
               existing_comment='CPU使用率，保留2位小数',
               existing_nullable=False)
        batch_op.alter_column('memory_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='Memory',
               existing_comment='内存使用率，保留2位小数',
               existing_nullable=False)
        batch_op.alter_column('disk_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='Disk',
               existing_comment='磁盘使用率，保留2位小数',
               existing_nullable=False)
        batch_op.alter_column('recorded_at',
               existing_type=mysql.DATETIME(),
               comment='记录时间',
               existing_comment='数据记录时间',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_monitor_data_recorded_at'), ['recorded_at'], unique=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True, comment='所属分组ID'))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True, comment='服务器描述'))
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(display_width=11),
               comment='SSH端口',
               existing_comment='SSH端口，默认22',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'server_groups', ['group_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user'),
               comment='用户角色',
               existing_comment='用户角色：管理员/普通用户',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user'),
               comment='用户角色：管理员/普通用户',
               existing_comment='用户角色',
               existing_nullable=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(display_width=11),
               comment='SSH端口，默认22',
               existing_comment='SSH端口',
               existing_nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('monitor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_data_recorded_at'))
        batch_op.alter_column('recorded_at',
               existing_type=mysql.DATETIME(),
               comment='数据记录时间',
               existing_comment='记录时间',
               existing_nullable=True)
        batch_op.alter_column('disk_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='磁盘使用率，保留2位小数',
               existing_comment='Disk',
               existing_nullable=False)
        batch_op.alter_column('memory_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='内存使用率，保留2位小数',
               existing_comment='Memory',
               existing_nullable=False)
        batch_op.alter_column('cpu_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='CPU使用率，保留2位小数',
               existing_comment='CPU',
               existing_nullable=False)

    op.drop_table('alert_rules')
    op.drop_table('alert_history')
    op.drop_table('server_groups')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
