"""empty message

Revision ID: 838e963da87a
Revises: 51ffba2471b7
Create Date: 2026-03-02 20:43:28.204401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838e963da87a'
down_revision = '51ffba2471b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.alter_column('silence_minutes',
               existing_type=mysql.INTEGER(display_width=11),
               comment='静默时间(分钟)避免频繁轰炸',
               existing_comment='静默时间(分钟)',
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='操作人ID(可为空,如系统自动任务)',
               existing_comment='操作人ID',
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=50),
               comment='动作(如:DELETE_SERVER)',
               existing_comment='动作',
               existing_nullable=False)
        batch_op.alter_column('target',
               existing_type=mysql.VARCHAR(length=100),
               comment='操作对象(如:server_id=5)',
               existing_comment='操作对象',
               existing_nullable=True)
        batch_op.alter_column('client_ip',
               existing_type=mysql.VARCHAR(length=45),
               comment='操作来源IP',
               existing_comment='来源IP',
               existing_nullable=True)

    with op.batch_alter_table('monitor_data', schema=None) as batch_op:
        batch_op.alter_column('cpu_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='CPU使用率，保留2位小数',
               existing_comment='CPU',
               existing_nullable=False)
        batch_op.alter_column('memory_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='内存使用率，保留2位小数',
               existing_comment='Memory',
               existing_nullable=False)
        batch_op.alter_column('disk_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='磁盘使用率，保留2位小数',
               existing_comment='Disk',
               existing_nullable=False)
        batch_op.alter_column('recorded_at',
               existing_type=mysql.DATETIME(),
               comment='数据记录时间',
               existing_comment='记录时间',
               existing_nullable=True)

    with op.batch_alter_table('server_groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称(如:后端组,大数据组)',
               existing_comment='分组名称',
               existing_nullable=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(display_width=11),
               comment='SSH端口，默认22',
               existing_comment='SSH端口',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               comment='服务器描述/用途备注',
               existing_comment='服务器描述',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user'),
               comment='用户角色：管理员/普通用户',
               existing_comment='用户角色',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user'),
               comment='用户角色',
               existing_comment='用户角色：管理员/普通用户',
               existing_nullable=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               comment='服务器描述',
               existing_comment='服务器描述/用途备注',
               existing_nullable=True)
        batch_op.alter_column('port',
               existing_type=mysql.INTEGER(display_width=11),
               comment='SSH端口',
               existing_comment='SSH端口，默认22',
               existing_nullable=True)

    with op.batch_alter_table('server_groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称',
               existing_comment='分组名称(如:后端组,大数据组)',
               existing_nullable=False)

    with op.batch_alter_table('monitor_data', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=mysql.DATETIME(),
               comment='记录时间',
               existing_comment='数据记录时间',
               existing_nullable=True)
        batch_op.alter_column('disk_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='Disk',
               existing_comment='磁盘使用率，保留2位小数',
               existing_nullable=False)
        batch_op.alter_column('memory_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='Memory',
               existing_comment='内存使用率，保留2位小数',
               existing_nullable=False)
        batch_op.alter_column('cpu_value',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='CPU',
               existing_comment='CPU使用率，保留2位小数',
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('client_ip',
               existing_type=mysql.VARCHAR(length=45),
               comment='来源IP',
               existing_comment='操作来源IP',
               existing_nullable=True)
        batch_op.alter_column('target',
               existing_type=mysql.VARCHAR(length=100),
               comment='操作对象',
               existing_comment='操作对象(如:server_id=5)',
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=50),
               comment='动作',
               existing_comment='动作(如:DELETE_SERVER)',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='操作人ID',
               existing_comment='操作人ID(可为空,如系统自动任务)',
               existing_nullable=True)

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.alter_column('silence_minutes',
               existing_type=mysql.INTEGER(display_width=11),
               comment='静默时间(分钟)',
               existing_comment='静默时间(分钟)避免频繁轰炸',
               existing_nullable=True)

    # ### end Alembic commands ###
