"""add table

Revision ID: b4f256badfeb
Revises: 
Create Date: 2025-10-05 21:05:56.669755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f256badfeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=False, comment='服务器名称'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP地址'),
    sa.Column('port', sa.Integer(), nullable=True, comment='SSH端口，默认22'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='告警邮箱'),
    sa.Column('role', sa.Enum('admin', 'user'), nullable=False, comment='用户角色：管理员/普通用户'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('monitor_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='关联的服务器ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='服务器IP地址'),
    sa.Column('cpu_value', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='CPU使用率，保留2位小数'),
    sa.Column('memory_value', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='内存使用率，保留2位小数'),
    sa.Column('disk_value', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='磁盘使用率，保留2位小数'),
    sa.Column('recorded_at', sa.DateTime(), nullable=True, comment='数据记录时间'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_users',
    sa.Column('server_id', sa.Integer(), nullable=False, comment='服务器ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='关联创建时间'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_users')
    op.drop_table('monitor_data')
    op.drop_table('users')
    op.drop_table('servers')
    # ### end Alembic commands ###
